version: '3.8'

services:
  squid:
    build: squid/.
    environment:
      - "DISK_CACHE_SIZE=5000"
      - "MAX_CACHE_OBJECT=1000"
      # - "SQUID_DIRECTIVES_ONLY=true"
      # - "SQUID_DIRECTIVES='refresh_pattern . 0 0 1 refresh-ims'"
    network_mode: "host"
    volumes:
      - squid_cache:/var/cache/squid

  tproxy:
    build: iptables_docker/.
    network_mode: "host"
    privileged: true

volumes:
  squid_cache:
